const express =require("express")
const router=express.Router()
const userpost=require("../controllers/user/userpost.cont")
const userget =require("../controllers/user/userget.cont")
const userselfget =require ("../controllers/user/userself.cont")
const userupdate = require("../controllers/user/userudt")
const userlogin =require("../controllers/user/userlogin.cont")
const userdlt = require("../controllers/user/userdlt.cont")
router.get("/", userget)
router.get("/:email", userselfget)
router.post("/", userpost )
router.post("/:email", userlogin)
router.put("/:email", userupdate )
router.delete("/:email", userdlt)

module.exports=router